### PR TITLE
Fix Slow Connectivity Crash

### PR DESCRIPTION
**Pull request by ferquies**
Add a function to check the internet availability and use it before make any network calls

#38

### CODE REVIEW

**Comment by ferquies** [comment]
Ok, I keep working on it

**Comment by DesignrKnight** [comment]
Any update?

**Comment by ferquies** [comment]
Sorry, I'd wrote a comment with doubts in the issue section and I think you didn't saw, I paste it here:
Ok, in Mentors section there are actually a button that indicates there is no internet connection. Did you mean we must show the "No internet connection" snackbar before open any section that needs internet or implement the snackbar inside each section?
And in case we must show the snackbar inside each screen, in the case of FAQ I have to show it in native.

**Comment by DesignrKnight** [comment]
A uniform snack-bar in all route/activity that shows no connectivity in case of lack of internet access is what we are expecting as an ideal solution.

**Comment by ferquies** [comment]
I maked another pull request at https://github.com/developer-student-clubs-nitr/project-avocado/pull/51

**Pull request closed without merging**
