### PR TITLE
Add Splash Screen

### PR DESCRIPTION
**Pull request by hkp27299**
Flare splash screen added working both with logged in or newly login

#32

### CODE REVIEW

**Comment by DesignrKnight** [comment]
Can you add a video or screenshots showcasing the change?

**Comment by hkp27299** [comment]
I cant send video on this please send me mail id

**Comment by DesignrKnight** [comment]
dsc.nitr@gmail.com

**Comment by hkp27299** [comment]
Check you mail

**Comment by hkp27299** [comment]
Bro any change or what i sent videos

**Comment by DesignrKnight** [comment]
Sorry for the delay, we need some changes. We'll get back to you with some design samples to ease the process

Thank you so much for the contribution

**Comment by DesignrKnight** [comment]
The fonts and the design language is not consistent with the present design of the app. Try to have a design that is matching. Instead of writing 'Welcome' a basic logo reveal animation would be sufficient

**Comment by hkp27299** [comment]
oky let me see

**Comment by DesignrKnight** [comment]
Any update...?

**Comment by hkp27299** [comment]
yah working some issue in animation.

**Comment by hkp27299** [comment]
Make new PR with splash screen

**Pull request closed without merging**
